#image: gitlab/dind
#services:
#  - docker:dind

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay

stages:
  - maven-build
  - docker-build

maven-build:
  stage: maven-build
  image: openjdk:11
  script: 
      - chmod +x mvnw
      - ./mvnw clean install
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s

docker-build:
  stage: docker-build
  image: jpetazzo/dind
  script:
    - ls -l
    - ls target/
    - docker info
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s