variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  
stages:
  - maven-build
  - docker-build

maven-build:
  stage: maven-build
  image: eclipse-temurin:11-jdk-alpine
  script: 
      - chmod +x mvnw
      - ./mvnw clean install
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s

docker-build:
  stage: docker-build
  image: docker:18.09.7-dind 
  services:
    - docker:18.09.7-dind
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - echo $CI_COMMIT_BRANCH
    - docker build -t spring-boot-sample:$CI_COMMIT_BRANCH .
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s