variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  
stages:
  - maven-build
  - docker-build

maven-build:
  stage: maven-build
  image: eclipse-temurin:11.0.16_8-jre-alpine
  script: 
      - chmod +x mvnw
      - ./mvnw clean install
      - sleep 3600
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s

docker-build:
  stage: docker-build
  image: docker:18.09.7-dind 
  services:
    - docker:18.09.7-dind
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - docker info
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s