variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_HOST: tcp://localhost:2375
  
stages:
  - maven-build
  - docker-build

maven-build:
  stage: maven-build
  image: openjdk:11
  script: 
      - chmod +x mvnw
      - ./mvnw clean install
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s

docker-build:
  stage: docker-build
  services:
    - docker:18.09.7-dind
  image: docker:18.09.7-dind 
 # image: docker:18.09.7
  script:
    - ls -l
    - ls target/
    - until docker info; do sleep 1; done
    - docker info
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-k8s